# Numpy

#### Numerical structure ---> Arrays ----> Linear algebra ---> Transformation ---> Matrices
#### Memory usage  and faster processing.
#### zip helps in iterating two list simentenosuly

In [2]:
import numpy as np
import time
import sys #  system based 

In [3]:
array=np.arange(100)
print("Memory size is:",array.size*array.itemsize)

Memory size is: 400


In [4]:
lis = range(0,100)

In [5]:
print("Memory size is:",sys.getsizeof(1)*len(lis))

Memory size is: 2800


In [9]:
## faster computation
size = 10000

list1 = range(size)
list2 = range(size)

arr1=np.arange(size)
arr2=np.arange(size)

In [10]:
start=time.time()
for x,y in zip(list1,list2):
    res = x+y
    
print("Time taken is ",(time.time()-start)*1000)

Time taken is  3.9794445037841797


In [11]:
start=time.time()
res=arr1+arr2
print("Time taken is ",(time.time()-start)*1000)

Time taken is  1.0199546813964844


## Creating Arrays

In [12]:
al = np.array([1,2,3])

In [14]:
al 

array([1, 2, 3])

In [15]:
type(al )

numpy.ndarray

In [ ]:
nd - n dimensional arrays - 1D,2D,3D - Tensors --  Rows,columns and depth

In [16]:
lst=[1,2,"Raj"]

In [19]:
type(lst[2])

str

In [20]:
arr=np.array([1,2,"Raj"])

In [21]:
print(type(arr[0]))

<class 'numpy.str_'>


In [23]:
arr_2d  = np.array([[1,2,4],[5,6,7]])

In [27]:
arr_2d

array([[1, 2, 4],
       [5, 6, 7]])

In [25]:
arr_2d.shape

(2, 3)

In [26]:
arr_2d[1,1]

6

In [31]:
arr_3 = ([[1,2,3],[9,3,9],[2,5,6]])

In [32]:
arr_3

[[1, 2, 3], [9, 3, 9], [2, 5, 6]]

##### Create an array with shape 2x4x4


In [42]:
arr_4=np.array([[[5,6,7,4],[6,7,6,8],[7,6,18,20],[8,67,78,90]],[[54,65,7,41],[64,75,6,81],[74,6,518,201],[82,673,781,950]]])



In [43]:
arr_4

array([[[  5,   6,   7,   4],
        [  6,   7,   6,   8],
        [  7,   6,  18,  20],
        [  8,  67,  78,  90]],

       [[ 54,  65,   7,  41],
        [ 64,  75,   6,  81],
        [ 74,   6, 518, 201],
        [ 82, 673, 781, 950]]])

In [44]:
arr_4.shape

(2, 4, 4)

In [46]:
arr_4(1,1)

TypeError: 'numpy.ndarray' object is not callable

##### Functios invloved in array

In [47]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [55]:
a.reshape((2,2,4))  #  size and row and columns

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [58]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [61]:
np.arange(0,100,10)  # start,stop and step

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
np.arange(12,39,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

#####  Zero matrix ----> fill all the elements with zero

In [66]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
a = np.ones((3,3))
x=np.pad(a,pad_width=1,mode='constant',constant_values=0)

In [69]:
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

##### Identity matrix  ---> which has diagonal elements as ones and others zeros. It should be square matrix

In [70]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Square matrix ---> rows and columns will be equal

In [79]:
p=np.diag((1,2,3,4,5,6))

In [72]:
arr_ = np.array([1,2,3,4])

In [73]:
dup=arr_.view()

In [74]:
dup

array([1, 2, 3, 4])

In [75]:
arr_ = np.array([1,2,3,4])
a=arr_.copy()
a[0]=19

In [76]:
arr_

array([1, 2, 3, 4])

In [77]:
a

array([19,  2,  3,  4])

In [78]:
for i in arr_:
    print(i)

1
2
3
4


In [81]:
for i in p:
    for j in i:
        print(j)

1
0
0
0
0
0
0
2
0
0
0
0
0
0
3
0
0
0
0
0
0
4
0
0
0
0
0
0
5
0
0
0
0
0
0
6


##### convert a list into array 
##### convert 2D array into list

In [84]:

  
# initilizing list  
ls = [[1, 7, 0], 
       [ 6, 2, 5]]  
  
# converting list to array  
ar = np.array(ls)

In [85]:
ar

array([[1, 7, 0],
       [6, 2, 5]])

In [89]:
tup=range(1,11)
arr_4=np.array(tup)
arr_4.reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [88]:
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Dot matrix ( Matrix multplcation) .Multple row with column and add to row

In [ ]:
np.dot(arr1,arr2)

In [91]:
arrr=np.array([1,2,3,4])
arrr1=np.array([6,7,8,9])

In [96]:
h = np.stack((arrr,arrr1),axis=1)

In [97]:
np.transpose(h)

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [99]:
np.concatenate((arrr,arr1))

array([   1,    2,    3, ..., 9997, 9998, 9999])